import React from "react";
import { Footer, Header } from "../components";
import { useRouter } from "next/router";
import { CategoryContent } from "../components/category";
import Head from "next/head";

const Category = () => {
  const router = useRouter();
  return (
    <div>
      <Head>
        <title>Category - Apple Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <CategoryContent category={router.query.category} />
      <Footer />
    </div>
  );
};

export default Category;
