import Head from "next/head";
import { Header, Iphone14Pro } from "../components";
import { AiFillApple } from "react-icons/ai";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home - Apple Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* Header */}
        <Header />

        {/* iPhone 14 Pro*/}
        <Iphone14Pro />
      </main>
    </>
  );
}
