import Head from "next/head";
import { Header } from "../components";
import { HomeImage } from "../components/home";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home - Apple Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* Header */}
        <Header />

        {/* Home Images */}
        {/* iPhone 14 Pro */}
        <HomeImage
          name="iPhone 14 Pro"
          title="Pro. Beyond."
          image="/img/iPhone14_pro.jpg"
          background={false}
        />

        {/* iPhone 14 */}
        <HomeImage
          name="iPhone 14"
          title="Big and bigger."
          image="/img/iPhone14.jpg"
          background={true}
        />
      </main>
    </>
  );
}
